name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to release (e.g., 1.0.0)'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare:
    name: Prepare Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update version and changelog
        run: npx release-it ${{ github.event.inputs.version }} --ci --no-git --no-github --no-npm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: release v${{ github.event.inputs.version }}"
          title: "chore: release v${{ github.event.inputs.version }}"
          body: |
            This PR contains the version bump and changelog for `v${{ github.event.inputs.version }}`.

            **Next Steps:**
            1. Merge this PR into `main`.
            2. From your local machine, pull the latest `main`.
            3. Run the following commands to trigger the publish workflow:
               ```sh
               git tag v${{ github.event.inputs.version }}
               git push origin v${{ github.event.inputs.version }}
               ```
          branch: "chore/release-v${{ github.event.inputs.version }}"
          base: "main"
          delete-branch: true
